version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-https
    restart: unless-stopped
    ports:
      - "6532:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    networks:
      - nginx-net

networks:
  nginx-net:
    driver: bridge
