server {
    listen 6532 ssl;
    server_name netdes.xyz www.netdes.xyz;

    ssl_certificate     /etc/letsencrypt/live/netdes.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/netdes.xyz/privkey.pem;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

    root  /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /health {
        access_log off;
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
